on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      #run: robot --version
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install RobotFramework
      run: |
        python -m pip install -U pip
        pip install robotframework
   # - name: Start UserAccount Project      
   #   run: mvnw spring-boot:run
   #   working-directory: ./UserAccounts
   # - name: Run RobotFramework Test Cases
   #   working-directory: ./UserAccountsTest
   #   run: robot -T UserAccountsTest.robot
